# Site settings
title: Gino Galotti
description: >- # this means to ignore newlines until "baseurl:"
  Always code as if the guy who ends up maintaining your code
  will be a violent psychopath who knows where you live.
baseurl: "/resume"  # the subpath of your site, e.g. /blog
url: "ginogalotti.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: ginogalotti/resume


# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name     : Gino Galotti
  image    : img/avatar
  email    : me@ginogalotti.com
  github   : ginogalotti
  linkedin : ginogalotti

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
permalink: blog/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock